datasources {
    default {
        driver-class-name="org.h2.Driver"
        url="jdbc:h2:mem:bloompath;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
        username="sa"
        password="password"
        dialect="H2"
    }
}
micronaut {
    application {
        name=bloompath
    }
    serde {
        serialization {
          inclusion: ALWAYS
       }
    }
}
langchain4j {
    in-memory {
        embedding-store {
            enabled = false
        }
    }
    ollama {
        base-url = "${OLLAMA_BASE_URL:`http://localhost:11434`}"
        model-name = "${OLLAMA_MODEL_NAME:`gemma4:e4b-mlx`}"
        chat-model {
            response-format = "json_object"
            timeout=2m
            log-requests = true
            log-responses = true
        }
    }
}
